---
- name: Enable kubelet
  ansible.builtin.systemd:
    name: kubelet
    state: started
    enabled: true
  become: true

- name: Enable containerd
  ansible.builtin.systemd:
    name: containerd
    state: started
    enabled: true
  become: true
