---
- name: Install git client
  block:
    - name: Find rpm packages
      ansible.builtin.find:
        paths:
          - "{{ ansible_home_directory }}/materials/rpm/git"
        patterns: "*.rpm"
      register: git_rpm_files

    - name: Define package paths from find results
      ansible.builtin.set_fact:
        git_rpm_package_paths: "{{ git_rpm_files.files | map(attribute='path') | list }}"

    - name: Install packages for git
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
        disable_gpg_check: true
      with_items: "{{ git_rpm_package_paths }}"
      become: true

    - name: Get version of git
      ansible.builtin.command: "git -v"
      changed_when: false
      register: git_version

    - name: Display version of git
      ansible.builtin.debug:
        msg: "{{ git_version }}"

    - name: Register enail address
      ansible.builtin.command: "git config --global user.email \"{{ management_email_address }}\""
      become: true

    - name: Register user name
      ansible.builtin.command: "git config --global user.name \"{{ ansible_user }}\""
      become: true

    - name: Check current configuration
      ansible.builtin.command: "git config -l"
      register: check_git_conf
      become: true

    - name: Display current configuration
      ansible.builtin.debug:
        msg: "{{ check_git_conf }}"
  rescue:
    - name: Uninstall packages for git
      ansible.builtin.dnf:
        name: "git"
        state: absent
      become: true
