---
- name: K8s master general setup
  block:
    - name: Load modules
      ansible.builtin.command: "modprobe {{ item }}"
      become: true
      with_items:
        - "overlay"
        - "br_netfilter"

    - name: Get loaded modules
      ansible.builtin.shell: "set -o pipefail ; lsmod | egrep 'overlay|br_netfilter'"
      become: true
      changed_when: false
      register: check_loaded_modules

    - name: Display loaded modules
      ansible.builtin.debug:
        msg: "{{ check_loaded_modules }}"
      when: check_loaded_modules is succeeded

    - name: Put /etc/modules-load.d/k8s.conf
      ansible.builtin.copy:
        src: mod_k8s.conf
        dest: /etc/modules-load.d/k8s.conf
        owner: root
        group: root
        mode: "0644"
      become: true

    - name: Slurp /etc/modules-load.d/k8s.conf
      ansible.builtin.slurp:
        path: /etc/modules-load.d/k8s.conf
      register: slurp_mod_k8sconf

    - name: Echo content of /etc/modules-load.d/k8s.conf
      ansible.builtin.debug:
        msg: "{{ slurp_mod_k8sconf.content | b64decode }}"

    - name: Put /etc/sysctl.d/k8s.conf
      ansible.builtin.copy:
        src: sysctl_k8s.conf
        dest: /etc/sysctl.d/k8s.conf
        owner: root
        group: root
        mode: "0644"
      become: true

    - name: Slurp /etc/sysctl.d/k8s.conf
      ansible.builtin.slurp:
        path: /etc/sysctl.d/k8s.conf
      register: slurp_sysctl_k8sconf

    - name: Echo content of /etc/sysctl.d/k8s.conf
      ansible.builtin.debug:
        msg: "{{ slurp_sysctl_k8sconf.content | b64decode }}"

    - name: Apply kernel parameter changes
      ansible.builtin.command: "sysctl --system"
      become: true

    - name: Check kernel parameters
      ansible.builtin.command: >
        sysctl
        net.bridge.bridge-nf-call-iptables
        net.bridge.bridge-nf-call-ip6tables
        net.ipv4.ip_forward
      register: check_kernel_parameters

    - name: Display kernel parameters
      ansible.builtin.debug:
        msg: "{{ check_kernel_parameters }}"
      when: check_kernel_parameters is succeeded
  rescue:
    - name: Unload modules
      ansible.builtin.command: "modprobe -r {{ item }}"
      with_items:
        - "overlay"
        - "br_netfilter"
      become: true

    - name: Remove /etc/modules-load.d/k8s.conf
      ansible.builtin.file:
        path: /etc/modules-load.d/k8s.conf
        state: absent
      become: true

    - name: Remove /etc/sysctl.d/k8s.conf
      ansible.builtin.file:
        path: /etc/sysctl.d/k8s.conf
        state: absent
      become: true

    - name: Apply kernel parameter changes
      ansible.builtin.command: "sysctl --system"
      become: true
