---
- name: Install packages for gitlab
  block:
    - name: Put repo file for gitlab
      ansible.builtin.template:
        src: gitlab_gitlab-ce.repo.j2
        dest: /etc/yum.repos.d/gitlab_gitlab-ce.repo
        owner: root
        group: root
        mode: "0644"
      become: true

    - name: Install gitlab packages
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      with_items: "{{ gitlab_packages }}"
      become: true

    - name: Enable postfix
      ansible.builtin.systemd:
        name: postfix
        state: started
        enabled: true
      become: true

    - name: Put configuration file
      ansible.builtin.template:
        src: gitlab.rb.j2
        dest: /etc/gitlab/gitlab.rb
        owner: root
        group: root
        mode: "0600"
      become: true

    - name: Apply configuration
      ansible.builtin.command: "gitlab-ctl reconfigure"
      become: true

    - name: Slurp Display messages
      ansible.builtin.debug:
        msg:
          - "Login with initial root pass and set up GitLab on web browser"
          - "You can find it on /etc/gitlab/initial_root_password"
  rescue:
    - name: Uninstall docker packages
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: absent
      with_items: "{{ gitlab_packages }}"
      become: true

    - name: Remove repo file
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "/etc/yum.repos.d/gitlab_gitlab-ce.repo"
        - "/etc/gitlab/gitlab.rb"
      become: true
