---
- name: Grep string "ipv6.disable=1" in /etc/default/grub
  ansible.builtin.command: "grep 'ipv6.disable=' /etc/default/grub"
  changed_when: false
  failed_when: false
  register: check_string_ingrubfile

- name: Slurp /etc/default/grub
  ansible.builtin.slurp:
    path: /etc/default/grub
  register: slurp_grubfile

- name: Echo content of /etc/default/grub
  ansible.builtin.debug:
    msg: "{{ slurp_grubfile.content | b64decode }}"

- name: Disable IPv6
  block:
    - name: Backup /etc/default/grub
      ansible.builtin.copy:
        src: /etc/default/grub
        dest: /etc/default/grub_org
        owner: root
        group: root
        mode: "0644"
        remote_src: true
        force: false
      become: true

    - name: Update grub settings
      ansible.builtin.lineinfile:
        backrefs: true
        dest: "/etc/default/grub"
        regexp: '^GRUB_CMDLINE_LINUX="(.*)"'
        line: 'GRUB_CMDLINE_LINUX="\1 ipv6.disable=1"'
        state: present
      become: true

    - name: Slurp /etc/default/grub (after)
      ansible.builtin.slurp:
        path: /etc/default/grub
      register: slurp_grubfile_after

    - name: Echo content of /etc/default/grub (after)
      ansible.builtin.debug:
        msg: "{{ slurp_grubfile_after.content | b64decode }}"

    - name: Update grub settings
      ansible.builtin.command: "grub2-mkconfig -o /boot/grub2/grub.cfg"
      become: true

    - name: Reboot host
      ansible.builtin.reboot:
        post_reboot_delay: 45
      async: 1
      poll: 0
      become: true

    - name: Wait for reboot
      ansible.builtin.wait_for_connection:
        delay: 30
        timeout: 300
  when: check_string_ingrubfile.rc != 0
  rescue:
    - name: Restore /etc/default/grub
      ansible.builtin.copy:
        src: /etc/default/grub_org
        dest: /etc/default/grub
        owner: root
        group: root
        mode: "0644"
        remote_src: true
        force: true
      become: true

    - name: Update grub settings
      ansible.builtin.command: "grub2-mkconfig -o /boot/grub2/grub.cfg"
      become: true
      notify:
        - Reboot host
        - Wait for reboot
