---
- name: Install serverspec
  block:
    - name: Find rpm packages
      ansible.builtin.find:
        paths:
          - "{{ ansible_home_directory }}/materials/rpm/rubygems"
        patterns: "*.rpm"
      register: ruby_rpm_files

    - name: Define package paths from find results
      ansible.builtin.set_fact:
        ruby_rpm_package_paths: "{{ ruby_rpm_files.files | map(attribute='path') | list }}"

    - name: Install packages for ruby
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
        disable_gpg_check: true
      with_items: "{{ ruby_rpm_package_paths }}"
      become: true

    - name: Find gem file
      ansible.builtin.find:
        paths:
          - "{{ ansible_home_directory }}/materials/gem/serverspec"
        patterns: "*.gem"
      register: serverspec_gem_files

    - name: Define file paths from find results
      ansible.builtin.set_fact:
        serverspec_gem_file_paths: "{{ serverspec_gem_files.files | map(attribute='path') | list }}"

    - name: Install packages for serverspec
      community.general.gem:
        name: serverspec
        gem_source: "{{ item }}"
        state: present
        install_dir: "{{ gem_install_dir }}"
        user_install: false
      with_items: "{{ serverspec_gem_file_paths }}"
      become: true

    - name: Check installed serverspec version
      ansible.builtin.shell: "set -o pipefail ; gem list | grep serverspec"
      register: check_serverspec_version
      changed_when: false

    - name: Display serverspec version
      ansible.builtin.debug:
        msg: "{{ check_serverspec_version }}"
  rescue:
    - name: Uninstall packages for serverspec
      community.general.gem:
        name: serverspec
        state: absent
        install_dir: "{{ gem_install_dir }}"
        user_install: false
      failed_when: false
      become: true

    - name: Uninstall packages for ruby
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: absent
      with_items:
        - ruby
        - rubygems
      failed_when: false
      become: true
