---
- name: Install kubernetes packages
  block:
    - name: Find rpm packages
      ansible.builtin.find:
        paths:
          - "{{ ansible_home_directory }}/materials/rpm/kubernetes-cni"
          - "{{ ansible_home_directory }}/materials/rpm/kubectl"
          - "{{ ansible_home_directory }}/materials/rpm/kubelet"
          - "{{ ansible_home_directory }}/materials/rpm/cri-tools"
          - "{{ ansible_home_directory }}/materials/rpm/kubeadm"
        patterns: "*.rpm"
      register: k8s_rpm_files
      delegate_to: localhost

    - name: Define package paths from find results
      ansible.builtin.set_fact:
        k8s_rpm_package_paths: "{{ k8s_rpm_files.files | map(attribute='path') | list }}"

    - name: Define package paths for target host
      ansible.builtin.set_fact:
        k8s_rpm_package_dest_paths: "{{ k8s_rpm_files.files | map(attribute='path') | map('dirname') | list }}"

    - name: Copy packages to target host
      ansible.builtin.copy:
        src: "{{ item.0 }}"
        dest: "{{ item.1 }}/"
        owner: ansible
        group: ansible
      with_together:
        - "{{ k8s_rpm_package_paths }}"
        - "{{ k8s_rpm_package_dest_paths }}"

    - name: Install packages for k8s
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
        disable_gpg_check: true
      with_items: "{{ k8s_rpm_package_paths }}"
      become: true

    - name: Enable kubelet
      ansible.builtin.systemd:
        name: kubelet
        state: started
        enabled: true
      become: true
  rescue:
    - name: Uninstall kubernetes packages
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: absent
      with_items:
        - kubernetes-cni
        - kubectl
        - kubelet
        - cri-tools
        - kubeadm
      become: true
