---
# note that this vars file is only used on playbook to create vm
# vars on this file are complemented with "playbooks/inventory/extra_vars/host_param.yml"
virt_install_param:
  hostname: "{{ host_parameters.test001v.hostname }}"
  ip_addr: "{{ host_parameters.test001v.ip_addr }}"
  netmask: "{{ host_parameters.test001v.netmask }}"
  gateway: "{{ host_parameters.test001v.gateway }}"
  vmsize: "30"
  vmcpu: "2"
  vmmemory: "2048"
  mac_addr: "{{ host_parameters.test001v.mac_addr }}"
  osvariant: "almalinux8"
  interface: "enp1s0"

virt_install_installed_packages:
  - "chrony"
  - "net-tools"
  - "cloud-utils-growpart"
  - "e2fsprogs"
  - "tar"
  - "jq"
