---
- name: Slurp /etc/resolv.conf
  ansible.builtin.slurp:
    path: /etc/resolv.conf
  register: slurp_resolvconf

- name: Echo content of /etc/resolv.conf
  ansible.builtin.debug:
    msg: "{{ slurp_resolvconf.content | b64decode }}"

- name: Backup /etc/resolv.conf
  ansible.builtin.copy:
    src: /etc/resolv.conf
    dest: /etc/resolv.conf_org
    owner: root
    group: root
    mode: "0644"
    remote_src: true
    force: false
  become: true

- name: Update /etc/resolv.conf
  block:
    - name: Update /etc/resolv.conf
      ansible.builtin.template:
        src: resolv.conf.j2
        dest: /etc/resolv.conf
        owner: root
        group: root
        mode: "0644"
      become: true
  rescue:
    - name: Restore /etc/resolv.conf
      ansible.builtin.copy:
        src: /etc/resolv.conf_org
        dest: /etc/resolv.conf
        owner: root
        group: root
        mode: "0644"
        remote_src: true
        force: true
      become: true

- name: Slurp /etc/resolv.conf (after)
  ansible.builtin.slurp:
    path: /etc/hosts
  register: slurp_resolvconf_after

- name: Echo content of /etc/resolv.conf (after)
  ansible.builtin.debug:
    msg: "{{ slurp_resolvconf_after.content | b64decode }}"
